import { Narrative, BranchNarrative } from './narrator.js';

export interface Slide {
  title: string;
  content: string;
  delay: number; // in milliseconds
}

export interface SlideShow {
  slides: Slide[];
  totalDuration: number;
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function formatBranch(branch: BranchNarrative): string {
  const lines: string[] = [];
  lines.push(`Branch: ${branch.branchName}`);
  lines.push(`Period: ${formatDate(branch.startDate)} - ${formatDate(branch.endDate)}`);
  lines.push(`Merges: ${branch.mergeCount}`);
  lines.push(`Key commits:`);
  for (const commit of branch.commits.slice(0, 5)) {
    lines.push(`  ${commit.hash.substring(0, 7)} - ${commit.message} (${commit.author})`);
  }
  if (branch.commits.length > 5) {
    lines.push(`  ... and ${branch.commits.length - 5} more`);
  }
  return lines.join('\n');
}

export function buildSlides(narrative: Narrative): SlideShow {
  const slides: Slide[] = [];

  // Title slide
  slides.push({
    title: narrative.title,
    content: narrative.summary,
    delay: 3000,
  });

  // Branch slides
  for (const branch of narrative.protagonistBranches) {
    slides.push({
      title: `Branch: ${branch.branchName}`,
      content: formatBranch(branch),
      delay: 4000,
    });
  }

  // Optional: conflict arcs
  if (narrative.conflictArcs && narrative.conflictArcs.length > 0) {
    for (const arc of narrative.conflictArcs) {
      const arcLines: string[] = [];
      arcLines.push(`Conflict: ${arc.description}`);
      arcLines.push(`Intensity: ${arc.severity}`);
      arcLines.push(`Branches involved: ${arc.branches.join(', ')}`);
      slides.push({
        title: `Conflict Arc: ${arc.description.substring(0, 40)}...`,
        content: arcLines.join('\n'),
        delay: 3000,
      });
    }
  }

  // Optional: merge storms
  if (narrative.mergeStorms && narrative.mergeStorms.length > 0) {
    for (const storm of narrative.mergeStorms) {
      const stormLines: string[] = [];
      stormLines.push(`Merge Storm: ${storm.description}`);
      stormLines.push(`Date: ${formatDate(storm.date)}`);
      stormLines.push(`Merges count: ${storm.mergeCount}`);
      slides.push({
        title: `Merge Storm: ${storm.description.substring(0, 40)}...`,
        content: stormLines.join('\n'),
        delay: 3000,
      });
    }
  }

  // Closing slide
  slides.push({
    title: 'The End',
    content: 'Generated by Git Graph Narrator',
    delay: 2000,
  });

  const totalDuration = slides.reduce((acc, s) => acc + s.delay, 0);

  return { slides, totalDuration };
}

export function renderSlide(slide: Slide): string {
  const separator = '='.repeat(60);
  return `${separator}\n${slide.title}\n${separator}\n\n${slide.content}\n\n${separator}`;
}

export function renderSlideShow(show: SlideShow): string {
  return show.slides.map(s => renderSlide(s)).join('\n\n***\n\n');
}

// Helper to simulate animated output (prints slide, then waits)
export function animateSlideShow(show: SlideShow, onSlide: (slide: Slide, index: number) => void): void {
  for (let i = 0; i < show.slides.length; i++) {
    onSlide(show.slides[i], i);
  }
}

// Export additional types for external use
export type { Narrative, BranchNarrative } from './narrator.js';
