import { Narrative, BranchArc, ConflictArc, PlotPoint } from './narrator.js';
import { CommitGraph } from './parser.js';

// ---------------------------------------------------------------------------
// Slide types
// ---------------------------------------------------------------------------

export interface Slide {
  lines: string[];
  delay: number; // ms
}

// ANSI escape codes for terminal cursor control and styling
const ESC = '\x1b';
const CSI = ESC + '[';

const CURSOR_HIDE = CSI + '?25l';
const CURSOR_SHOW = CSI + '?25h';
const CLEAR_SCREEN = CSI + '2J';
const HOME = CSI + 'H';
const RESET = CSI + '0m';

// Simple color theme
const COLORS = {
  title: CSI + '1;34m',     // bold blue
  subtitle: CSI + '36m',    // cyan
  branch: CSI + '33m',      // yellow
  commit: CSI + '32m',      // green
  weight: CSI + '35m',      // magenta
  conflict: CSI + '31m',    // red
  refactor: CSI + '33m',    // yellow
  dim: CSI + '2m',          // dim
  reset: RESET,
};

// ---------------------------------------------------------------------------
// Build slides from narrative
// ---------------------------------------------------------------------------

function buildTitleSlide(narrative: Narrative): Slide {
  const lines: string[] = [
    '',
    COLORS.title + '  ' + narrative.title + COLORS.reset,
    '',
    COLORS.subtitle + '  ' + narrative.summary + COLORS.reset,
    '',
    COLORS.dim + '  (Press Ctrl+C to exit)' + COLORS.reset,
    '',
  ];
  return { lines, delay: 4000 };
}

function buildBranchSlides(narrative: Narrative): Slide[] {
  const slides: Slide[] = [];

  for (const arc of narrative.protagonistBranches) {
    const lines: string[] = [];
    const lifespan = Math.round(arc.lifespanDays);

    lines.push('');
    lines.push(COLORS.branch + '  Branch: ' + arc.branchName + COLORS.reset);
    lines.push(COLORS.dim + '  Classification: ' + arc.classification + ' | Merges: ' + arc.mergeCount + ' | Lifespan: ' + lifespan + ' days' + COLORS.reset);
    lines.push('');

    // Show up to 5 most important commits (by weight)
    const topCommits = [...arc.commits]
      .sort((a, b) => b.weight - a.weight)
      .slice(0, 5);

    for (const commit of topCommits) {
      const dateStr = commit.date.toISOString().split('T')[0];
      lines.push(
        '    ' + COLORS.commit + commit.hash.slice(0, 7) + COLORS.reset +
        ' | ' + COLORS.dim + dateStr + COLORS.reset +
        ' | ' + commit.message +
        ' ' + COLORS.weight + '(' + (commit.weight >= 2.0 ? 'high' : 'low') + ')' + COLORS.reset
      );
    }

    if (arc.commits.length > 5) {
      lines.push(COLORS.dim + '    ... and ' + (arc.commits.length - 5) + ' more commits' + COLORS.reset);
    }

    lines.push('');
    slides.push({ lines, delay: 3000 });
  }

  return slides;
}

function buildConflictSlides(narrative: Narrative): Slide[] {
  const slides: Slide[] = [];

  if (narrative.conflictArcs.length === 0) {
    return slides;
  }

  for (const conflict of narrative.conflictArcs) {
    const lines: string[] = [];
    lines.push('');
    lines.push(COLORS.conflict + '  Conflict Arc' + COLORS.reset);
    lines.push('  Branches: ' + conflict.branches.join(', '));
    lines.push('  ' + conflict.description);
    lines.push('');
    slides.push({ lines, delay: 2500 });
  }

  return slides;
}

function buildRefactorSlides(narrative: Narrative): Slide[] {
  const slides: Slide[] = [];

  if (narrative.refactorHotspots.length === 0) {
    return slides;
  }

  for (const hotspot of narrative.refactorHotspots) {
    const lines: string[] = [];
    lines.push('');
    lines.push(COLORS.refactor + '  Refactor Hotspot' + COLORS.reset);
    lines.push('  Branch: ' + hotspot.branchName);
    lines.push('  ' + hotspot.description);
    lines.push('');
    slides.push({ lines, delay: 2500 });
  }

  return slides;
}

function buildStatsSlide(narrative: Narrative): Slide {
  const totalCommits = narrative.protagonistBranches.reduce(
    (sum, arc) => sum + arc.commits.length,
    0
  );
  const totalBranches = narrative.protagonistBranches.length;
  const totalConflicts = narrative.conflictArcs.length;
  const totalRefactors = narrative.refactorHotspots.length;

  const lines: string[] = [
    '',
    COLORS.subtitle + '  Repository Statistics' + COLORS.reset,
    '',
    '    Total commits analyzed: ' + totalCommits,
    '    Branches:               ' + totalBranches,
    '    Conflict arcs:          ' + totalConflicts,
    '    Refactor hotspots:      ' + totalRefactors,
    '',
    COLORS.dim + '  Generated by Git Graph Narrator' + COLORS.reset,
    '',
  ];
  return { lines, delay: 5000 };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function buildSlides(narrative: Narrative, graph: CommitGraph): Slide[] {
  const slides: Slide[] = [];

  slides.push(buildTitleSlide(narrative));
  slides.push(...buildBranchSlides(narrative));
  slides.push(...buildConflictSlides(narrative));
  slides.push(...buildRefactorSlides(narrative));
  slides.push(buildStatsSlide(narrative));

  return slides;
}

/**
 * Render slides to stdout with cursor control and delays.
 * This is a synchronous blocking render — suitable for CLI usage.
 */
export function renderSlides(slides: Slide[]): void {
  // Hide cursor
  process.stdout.write(CURSOR_HIDE);

  for (const slide of slides) {
    // Clear screen and move to home
    process.stdout.write(CLEAR_SCREEN + HOME);

    // Write slide content
    for (const line of slide.lines) {
      process.stdout.write(line + '\
');
    }

    // Wait for the delay
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, slide.delay);
  }

  // Final clear and show cursor
  process.stdout.write(CLEAR_SCREEN + HOME);
  process.stdout.write(CURSOR_SHOW);
}